name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v4.2.2
      
      - uses: gautamkrishnar/recent-activity@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          COMMIT_MSG: false
